[package]
name = "mini_haskell_lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
insta = { workspace = true, features = ["glob"] }
testsuite = { version = "0.1.0", workspace = true }
testsuite_macros = { version = "0.1.0", workspace = true }
